[General]
network = src.SimpleIntersectionScenario
sim-time-limit = 200s

debug-on-errors = true
print-undisposed = true

*.manager.host = "127.0.0.1"
*.manager.port = 9999
*.manager.updateInterval = 0.1s
*.manager.autoShutdown = true
*.manager.launchConfig = xmldoc("scenarios/simple.launchd.xml")

*.playgroundSizeX = 1000m
*.playgroundSizeY = 1000m
*.playgroundSizeZ = 50m

*.annotations.draw = true

# RSU position
*.rsu[0].mobility.x = 500
*.rsu[0].mobility.y = 500
*.rsu[0].mobility.z = 3

# Applications
*.node[*].applType = "adaptive.VehicleApp"
*.rsu[*].applType = "adaptive.AdaptiveRSUApp"

*.node[*].appl.headerLength = 80 bit
*.rsu[*].appl.headerLength = 80 bit

*.node[*].appl.sendBeacons = false
*.rsu[*].appl.sendBeacons = false
*.node[*].appl.dataOnSch = false
*.rsu[*].appl.dataOnSch = false

# Wireless
*.connectionManager.sendDirect = true
*.connectionManager.maxInterfDist = 1000m
*.connectionManager.drawMaxIntfDist = false

*.**.nic.mac1609_4.useServiceChannel = false
*.**.nic.mac1609_4.txPower = 20mW
*.**.nic.mac1609_4.bitrate = 6Mbps
*.**.nic.phy80211p.minPowerLevel = -110dBm

*.**.nic.phy80211p.useNoiseFloor = true
*.**.nic.phy80211p.noiseFloor = -98dBm

*.node[*].veinsmobility.setHostSpeed = false

